const paragraphs = [
  "India is our nation. It is located in the center of South Asia. In world, Republic of India is the seventh largest country by area and the second most populated country after China. India takes honour in being the largest democracy in the world. India is a diverse country with diverse cultures, languages, climates and geography. India is a federation under republic government governed under parliamentary system. There are twenty nine states and seven union territories in India. The national capital of India is Delhi.India is well known for its rich culture and cuisines, diverse wildlife, flora and fauna as well as for its genius minds that have made us proud around the globe.",

  "India is a vast country with second highest population in the world. It is a country with diverse cultures, traditions and beliefs. People in India celebrate unity in diversity. Festivals like Diwali, Holi, Navratri, Ramzan, Christmas etc. are celebrated by people across India and create a sense of brotherhood and cultural unity. Each festival has its religious and cultural importance.India is the land of diverse people belonging to various religions and speaking different languages. Our national language is Hindi. However, there are 22 different official languages spoken in India. It is the birth place of religions such as Hinduism, Buddhism, Jainism, and Sikhism. People in India have diverse dressing styles, different food habits and customs that differ from place to place. Indian cuisine is famous across the world. People with different castes, creed, colour, cultures and customs live in harmony in this India. It is a perfect example of unity in diversity.",

  "India is the land of festivals and vibrant colours of life. People of different religions and communities live here. Different festivals are celebrated with lots of enthusiasm, zeal and joy. People dress in different styles and dresses to celebrate these festivals.",

  "India attained Independence from British Rule on 15th of August 1947 following Independence movement that largely comprised of non-violence and civil disobedience. Independence accompanied the partition of India on religious lines in two dominions – India and Pakistan. Partition also gave rise to violent riots and mass afflictions. Our Prime Mister Jawaharlal Nehru, the first prime minister of Independent India hoisted the Indian National flag on Red Fort, Delhi on 15th August 1947. Every year 15th August is celebrated as Independence Day and is declared national holiday.",

  "Republic Day is celebrated on 26th January 1950 when constitution of India came in to effect with democratic government system initiating thenation’s transition towards being an independent republic. 26th of January has been declared as Republic Day as in 1930 on this day declaration of Purna Swaraj (Independence) was claimed.",

  "Gandhi Jayanti is celebrated on second of October, our national leader and freedom fighter Mahatma Gandhi’s birthday.There is nationwide holiday on National festivals. Religious festivals like Diwali, Holi, Raksha Bandhan, Christmas, Ramzan, Guru Nanak Jayanti, Ganesh Chaturthi, Baisakhi, Bihu, Pongal, Basant Panchami and many more are celebrated here with love and unity.",

  "India is an ethnically diverse country. People in India follow different religions and speak different languages. Among other things, India is known for its beautiful monuments, temples and historical buildings. Music, dance, cinema and sports are the essence of India.",

  "India attracts many tourists from across the world. It is well-known for its historical buildings built centuries ago. Some of its well known historical monuments include Taj Mahal in Agra, Qutub Minar in Delhi, Amer Fort in Rajasthan, Ajanta and Ellora Caves in Maharashtra, Virupaksha Temple in Karnataka, Kornak Temple in Odisha. These monuments attract many tourists and devotees from around the globe.Indian architecture is a fusion of local ancient traditions and imported styles. The vernacular architecture blends regional flavours. Taj Mahal is the most admired architectural piece in the world.",

  "Our country India is a unique country. Its culture has influenced nations across the border. India has tropical kind of climate since most part of the country lies within the trophies. The mountain ranges and the rain bearing winds influence the climate of our country. Alteration of seasons is the main feature of India.",
];
